services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-portfolio
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=portfolio123
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
